### ISSUE TITLE
Cannot run program "lsif-semanticdb", No such file or directory

### ISSUE THREAD

**Issue by ToughK** [sourcegraph/lsif-java#118]
I used the following command to install lsif-java on my machine.
```
# macOS
curl -Lo lsif-java https://github.com/sourcegraph/lsif-java/releases/download/v0.2.0/lsif-java-x86_64-apple-darwin \
  && chmod +x lsif-java \
  && ./lsif-java --help

```
But when I tried to generate lsif index in my repository it failed, throwing execeptions descriped below. 

```
info: lsif-semanticdb --out=/Users/xxx/dump.lsif --semanticdbDir=/Users/xxx/target/semanticdb-targetroot
java.io.IOException: Cannot run program "lsif-semanticdb" (in directory "/Users/xxx"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at os.proc.proc$lzycompute$1(ProcessOps.scala:128)
	at os.proc.proc$1(ProcessOps.scala:122)
	at os.proc.spawn(ProcessOps.scala:135)
	at moped.cli.SpawnableProcess.spawn(Processes.scala:161)
	at moped.cli.SpawnableProcess.call(Processes.scala:89)
	at com.sourcegraph.lsif_java.IndexCommand.process(IndexCommand.scala:67)
	at com.sourcegraph.lsif_java.IndexCommand.run(IndexCommand.scala:154)
	at moped.cli.Command.$anonfun$runAsFuture$1(BaseCommand.scala:14)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.scala:17)
	at scala.util.Try$.apply(Try.scala:210)
	at moped.cli.Command.runAsFuture(BaseCommand.scala:14)
	at moped.cli.Application$.$anonfun$run$7(Application.scala:317)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.io.IOException: error=2, No such file or directory
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_io_IOException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.lang.ProcessImpl.forkAndExec(ProcessImpl.java)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 22 more
```

**Comment by ToughK** [comment]
> [lsif-semanticdb](https://github.com/sourcegraph/lsif-semanticdb) has to be installed separately (currently no binary releases so requires a working Go installation to install).
> 
> It appears we don't mention this on the lsif-java install page, so thats on us 🙂 We may clarify that in the docs in the meantime, however we are rewriting lsif-semanticdb in Java so that it no longer needs to be installed separately and will be included in lsif-java (meaning we would then have to undo adding that step to the docs).

Thanks a lot. I guess maybe I was too early to to use lsif-java😹. I'll install lsif-semanticdb to try it out and give feedbacks if I meet any problem🙂

**Comment by Strum355** [comment]
This issue has been resolved as of a few versions. We no longer ship lsif-java as a native binary (due to performance reasons), so please reconsult the website for installation instructions :slightly_smiling_face: Coursier method is recommended but not required.
