### ISSUE TITLE
missing classes with same names

### ISSUE THREAD

**Issue by zhouang777** [sourcegraph/lsif-java#15]
Environment JDK 1.8

I'v been using lsif-java to generate a lsif dump to our java project, but I found that some classes were not been indexed correctly. These classes have same class names but in different packages.
I have been create a simple project to recreate this scenario. see https://github.com/zhouang777/multi-package-demo/tree/master.

--------------------------------
I have dig into code and found something might be useful.
1.  "typeByFile" in ProjectIndexer **already missing a class**. It should be 2 TestClass in the map. 
![image](https://user-images.githubusercontent.com/19465959/71349363-cbf8c380-25a9-11ea-9526-25e61854cd8f.png)

2.  I have tried to disable the spoon environment "ignoreDuplicateDeclarations". It comes to an spoon/JDT error 
```Running JVM 1.8.0_102
Exception in thread "main" spoon.compiler.ModelBuildingException: The type TestClass is already defined
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblem(JDTBasedSpoonCompiler.java:575)
	at spoon.support.compiler.jdt.TreeBuilderRequestor.acceptResult(TreeBuilderRequestor.java:27)
	at spoon.support.compiler.jdt.TreeBuilderCompiler.buildUnits(TreeBuilderCompiler.java:86)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:255)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:403)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:362)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:330)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:96)
	at spoon.Launcher.buildModel(Launcher.java:766)
	at ProjectIndexer.index(ProjectIndexer.java:43)
	at Main.main(Main.java:16)
```
It seems that spoon use only **simple class name** to identifier a type, not with package name prefixed. Not sure what is the root cause.

Do you guys have any suggestions?

**Comment by zhouang777** [comment]
When debug into JDT code，I found that JDT relay on package name to identify  a unique "TYPE". 
In this case, I  did not add package name in java file **explicitly**. which cause JDT recognize the two class as duplicated...
Sorry, my bad, I will close this issue.
