### ISSUE TITLE
Exception indexing google/guava repo from parsing descriptor from a local symbol

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#150]
```
$ lsif-java index
...
        Generating LSIF... [          ] 0%   8 files processedjava.lang.IllegalArgumentException: invalid symbol format
[error] local4
[error]      ^
[error] 	at com.sourcegraph.lsif_semanticdb.SymbolDescriptor$Parser.fail(SymbolDescriptor.java:46)
[error] 	at com.sourcegraph.lsif_semanticdb.SymbolDescriptor$Parser.parseDescriptor(SymbolDescriptor.java:117)
[error] 	at com.sourcegraph.lsif_semanticdb.SymbolDescriptor$Parser.entryPoint(SymbolDescriptor.java:34)
[error] 	at com.sourcegraph.lsif_semanticdb.SymbolDescriptor.parseFromSymbol(SymbolDescriptor.java:16)
[error] 	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.symbolDisplayName(SignatureFormatter.java:363)
[error] 	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatType(SignatureFormatter.java:245)
```

For local symbols, you need to look up in the symbol table to get the descriptor name.

**Comment by olafurpg** [comment]
I have a pending fix for this issue. Hit on it while indexing the JDK.
