### ISSUE TITLE
Unable to generate LSIF dump for INRIA/spoon

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/lsif-java#17]
I was curious about using this for spoon. JDT issue?

```
Exception in thread "main" java.lang.NullPointerException
	at spoon.support.compiler.jdt.JDTCommentBuilder$1.visitCtSwitch(JDTCommentBuilder.java:349)
	at spoon.support.reflect.code.CtSwitchImpl.accept(CtSwitchImpl.java:33)
	at spoon.reflect.visitor.CtInheritanceScanner.scan(CtInheritanceScanner.java:173)
	at spoon.support.compiler.jdt.JDTCommentBuilder$1.scan(JDTCommentBuilder.java:224)
	at spoon.support.compiler.jdt.JDTCommentBuilder.insertCommentInAST(JDTCommentBuilder.java:459)
	at spoon.support.compiler.jdt.JDTCommentBuilder.buildComment(JDTCommentBuilder.java:138)
	at spoon.support.compiler.jdt.JDTCommentBuilder.build(JDTCommentBuilder.java:102)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.lambda$buildModel$2(JDTBasedSpoonCompiler.java:433)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.forEachCompilationUnit(JDTBasedSpoonCompiler.java:450)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildModel(JDTBasedSpoonCompiler.java:432)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:365)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:330)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:113)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:96)
	at spoon.Launcher.buildModel(Launcher.java:766)
	at ProjectIndexer.index(ProjectIndexer.java:43)
	at Main.main(Main.java:16)
```

Command:

~/lsif-java/build/install/lsifjava/bin/lsifjava -projectRoot . -out dump.lsif

**Comment by monperrus** [comment]
> I was curious about using this for spoon

Cool :)

JDTCommentBuilder often crashes because JDT gives us lots of null everywhere, wand Spoon is not protected against all of them.

This is a potential solution: https://github.com/INRIA/spoon/pull/3277

**Comment by rvantonder** [comment]
@monperrus thanks a lot! I'm going to try out that solution and see if it gets past all the errors.

**Comment by monperrus** [comment]
#3277 merged, you can try with latest snapshot

**Comment by rvantonder** [comment]
@monperrus it works! Apologies for the slow turnaround. Here's some high level differences that the LSIF dump gives:

Left: with basic code intel (search  based, imprecise, without spoon). Right: Using spoon to generate type/doc annotations and dumping to LSIF

![Screen Shot 2020-03-13 at 2 11 01 PM](https://user-images.githubusercontent.com/888624/76660780-f3bb5000-6536-11ea-9b37-b81d2b23b3b7.png)

In other cases, it's possible to jump precisely to the definition of something, which otherwise turns up a bunch of suggestions that we can't be confident about. Here's one example where we can jump to a local definition using the spoon LSIF dump (which we couldn't do otherwise):

![j2d-invocations](https://user-images.githubusercontent.com/888624/76660899-409f2680-6537-11ea-8b70-0fe0a7dcd9e7.gif)

In other cases, we can precisely jump to the definition across files:

With the 'basic' code intelligence doing the above will give a list of possibilities (we can't be precise):
![j2d-x-file-800](https://user-images.githubusercontent.com/888624/76660921-53196000-6537-11ea-9e39-8e5ea6cbc605.gif)

There _are_ cases where the basic code intel will turn up useful results that are not in the LSIF dump. These are areas for us to continue improving. 

I'll try bundle up `lsif-java` as a GitHub action ASAP so it should be as simple one simple PR to get continuous intelligence for Spoon (or any other Java project on GH, which will use spoon to get code intel!). One of the best features is that once the dumps are uploaded per commit, it works on PRs and branches.

For now, I tested against my fork of spoon. The images/gifs above were tested against a commit with LSIF, so to see for yourself:

https://sourcegraph.com/github.com/rvantonder/spoon@master/-/blob/src/main/java/spoon/refactoring/MethodInvocationSearch.java#L59:64

And working on GitHub, if you have the Chrome/FF plugin: https://github.com/rvantonder/spoon/blob/master/src/main/java/spoon/refactoring/MethodInvocationSearch.java#L59

and then another commit where we don't have LSIF, and fall back to basic code intel heuristics:

https://sourcegraph.com/github.com/INRIA/spoon@master/-/blob/src/main/java/spoon/refactoring/MethodInvocationSearch.java#L59:64

On GH: https://github.com/INRIA/spoon/blob/master/src/main/java/spoon/refactoring/MethodInvocationSearch.java#L59

**Comment by rvantonder** [comment]
And: Thank you!

**Comment by monperrus** [comment]
Excellent.

> I'll try bundle up lsif-java as a GitHub action ASAP so it should be as simple one simple PR to get continuous intelligence for Spoon

Looking forward to it!
