### ISSUE TITLE
ClassCastException: com.sun.tools.javac.tree.JCTree$JCLiteral cannot be cast to com.sun.tools.javac.tree.JCTree$JCAssign

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#186]
```
 java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCLiteral cannot be cast to com.sun.tools.javac.tree.JCTree$JCAssign

        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.semanticdbAnnotation (SemanticdbVisitor.java:399)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.semanticdbAnnotations (SemanticdbVisitor.java:384)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.emitSymbolInformation (SemanticdbVisitor.java:98)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.emitSymbolOccurrence (SemanticdbVisitor.java:87)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.visitVariable (SemanticdbVisitor.java:196)
        at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.visitVariable (SemanticdbVisitor.java:29) 
```

**Comment by olafurpg** [comment]
Discovered while indexing repos on packagehub

**Comment by Strum355** [comment]
Do you know what repo that was for?

**Comment by olafurpg** [comment]
I can't find it from the logs. I'm also seeing this cast here
```
ClassCastException: com.sun.tools.javac.tree.JCTree$JCFieldAccess cannot be cast to com.sun.tools.javac.tree.JCTree$JCAssign
	at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.semanticdbAnnotation(SemanticdbVisitor.java:399)
	at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.semanticdbAnnotations(SemanticdbVisitor.java:384)
	at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.emitSymbolInformation(SemanticdbVisitor.java:98)
	at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.emitSymbolOccurrence(SemanticdbVisitor.java:87)
	at com.sourcegraph.semanticdb_javac.SemanticdbVisitor.visitClass(SemanticdbVisitor.java:149)
```
