### ISSUE TITLE
Java 17 support

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#263]
Java 17 will be released soon. We should make sure that lsif-java works with Java 17 once it's available. Opening this issue to track this topic.

- [x] Wait for Java 17 to become available in Coursier https://github.com/coursier/jvm-index/pull/52
- [x] Test with Zulu 17, it works without issues
- [x] Wait for Temurin 17 to become available https://github.com/coursier/jvm-index/pull/53
- [x] Update `roundToNearestStableRelease` https://github.com/sourcegraph/lsif-java/blob/02ccd70f1c08bba932693e9793d214207979a990/lsif-semanticdb/src/main/java/com/sourcegraph/lsif_semanticdb/JavaVersion.java#L43
- [x] Automatically add missing JVM options to include exports for `jdk.compiler` APIs when indexing Gradle/Maven/sbt projects
```
--add-exports jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
--add-exports jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED
```
- [x] Make the SemanticDB compiler plugin work with Java 17 (handle breaking changes)
```
Caused by: java.lang.NoSuchMethodError: 'boolean com.sun.tools.javac.code.Symbol.isLocal()'
	at com.sourcegraph.semanticdb_javac.GlobalSymbolsCache.isLocalVariable(GlobalSymbolsCache.java:60)
	at com.sourcegraph.semanticdb_javac.GlobalSymbolsCache.uncachedSemanticdbSymbol(GlobalSymbolsCache.java:46)
```

**Comment by olafurpg** [comment]
Fixed in #355 where we added updated the Docker container to automatically add the necessary JVM options when the Java version is 17. This issue is not fixed in the general case since we can't control how users install lsif-java. Users who launch lsif-java directly may still need to configure `JAVA_OPTS` to include the `--add-exports` flags above.
