### ISSUE TITLE
FileSystemNotFoundException: unable to use semanticdb-javac with sbt 

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#288]
```
Please report a bug to https://github.com/sourcegraph/semanticdb-java with the stack trace above.
java.nio.file.FileSystemNotFoundException: Provider "vf" not installed
	at java.nio.file.Paths.get(Paths.java:147)
	at com.sourcegraph.semanticdb_javac.SemanticdbTaskListener.semanticdbOutputPath(SemanticdbTaskListener.java:77)
	at com.sourcegraph.semanticdb_javac.SemanticdbTaskListener.onFinishedAnalyze(SemanticdbTaskListener.java:55)
	at com.sourcegraph.semanticdb_javac.SemanticdbTaskListener.finished(SemanticdbTaskListener.java:45)
```

Workaround is to configure the build to fork Java compilation by setting `javaHome` like here
https://github.com/sourcegraph/lsif-java/blob/bbe2b1fcd03b8729465ac777b9f5dd500c613e8e/project/JavaToolchainPlugin.scala#L39

**Comment by olafurpg** [comment]
Fixed in https://github.com/sourcegraph/lsif-java/pull/292

Requires the `-build-tool:sbt` option in `"-Xplugin:semanticdb -build-tool:sbt"`
