### ISSUE TITLE
SignatureFormatterException: constant was not of known type 11

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#297]
```
Caused by: com.sourcegraph.lsif_semanticdb.SignatureFormatterException: failed to format symbol 'akka/stream/impl/fusing/GraphInterpreter.NoEvent.'
symbol: "akka/stream/impl/fusing/GraphInterpreter.NoEvent."
kind: METHOD
properties: 1032
display_name: "NoEvent"
language: SCALA
signature {
  method_signature {
    type_parameters {
    }
    return_type {
      constant_type {
        constant {
          11: {
          }
        }
      }
    }
  }
}
access {
  public_access {
  }
}

Caused by: java.lang.IllegalArgumentException: constant was not of known type 11: {
}

	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatConstant(SignatureFormatter.java:494)
	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatType(SignatureFormatter.java:597)
	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatScalaMethodSignature(SignatureFormatter.java:283)
	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatMethodSignature(SignatureFormatter.java:211)
	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatSymbolUnsafe(SignatureFormatter.java:67)
	at com.sourcegraph.lsif_semanticdb.SignatureFormatter.formatSymbol(SignatureFormatter.java:56)
```

**Comment by olafurpg** [comment]
Fixed in #300
