### ISSUE TITLE
IllegalAccessError: cannot access class com.sun.tools.javac.api.BasicJavacTask

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/lsif-java#320]
Using Java 16 to index the elasticsearch repo
```
$ eval "$(cs java --jvm 16 --env)"
$ lsif-java index
...
> Task :build-conventions:compileJava FAILED
warning: [options] system modules path not set in conjunction with -source 11
Exception in thread "main" java.lang.IllegalAccessError: class com.sourcegraph.semanticdb_javac.SemanticdbPlugin (in unnamed module @0x527740a2) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x527740a2
	at com.sourcegraph.semanticdb_javac.SemanticdbPlugin.init(SemanticdbPlugin.java:19)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:229)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:292)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**Comment by olafurpg** [comment]
Duplicate of #263
