### ISSUE TITLE
NullPointer exception if class extends generic class

### ISSUE THREAD

**Issue by fenuks** [sourcegraph/lsif-java#43]
## Platform
Linux

## Java info
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10)
OpenJDK 64-Bit Server VM (build 11.0.8+10, mixed mode)

## Description

NPE occurs with stack trace
```
Exception in thread "main" java.lang.NullPointerException
	at lsifjava.DocumentIndexer.getLocalizedName(DocumentIndexer.java:514)
	at lsifjava.DocumentIndexer.appendTypeParam(DocumentIndexer.java:505)
	at lsifjava.DocumentIndexer.mkClassDoc(DocumentIndexer.java:462)
	at lsifjava.DocumentIndexer.access$600(DocumentIndexer.java:19)
	at lsifjava.DocumentIndexer$DefinitionsVisitor.visitCtClass(DocumentIndexer.java:205)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:58)
	at lsifjava.DocumentIndexer.visitDefinitions(DocumentIndexer.java:55)
	at lsifjava.ProjectIndexer.index(ProjectIndexer.java:125)
	at lsifjava.Main.main(Main.java:19)
```

when class extends other generic class, e.g. this triggers error:

```java
package org.example;

import java.util.ArrayList;

public class TestList<T extends Integer> extends ArrayList<T> {}
```

**Comment by fenuks** [comment]
I believe #46 fixes this error.
